---
# roles/common/defaults/main.yml
common_timezone: UTC

lc_lang: "en_US.UTF-8"
lc_all: "en_US.utf8"
lc_ctype: "en_US.utf8"
lc_collate: "en_US.utf8"

base_ubuntu:
  common:
    apt_packages:
      - build-essential
      - git
      - mcrypt
      - nginx
      - curl