---

- name: get the latest code
  git: repo={{ project_repo_url }} dest={{ project_path }} version={{ repo_version }} accept_hostkey=true
  become: false
  tags: ['always']

- name: install packages based on package.json.
  npm: path={{ project_path }} global=no
  become: true
  tags: ['deploy']

- name: build in project folder
  command: chdir={{ project_path }} grunt
  become: false
  tags: ['deploy']

- name: start node apps
  command: chdir={{ project_path }} pm2 start --interpreter babel-node --name="{{ project_name }}" {{ main_project_file }}
  become: false
  tags: ['deploy']
  environment:
    NODE_ENV: '{{ node_env }}'

