---

- name: get the latest code
  git: repo={{ project_repo_url }} dest={{ project_path }} version={{ repo_version }} accept_hostkey=true
  become: false
  tags: ['always']

- name: install packages based on package.json.
  npm: path={{ project_path }} global=no
  become: true
  tags: ['deploy']

- name: install grunt & pm2 globally
  become: true
  npm: name="{{ item }}" global=yes production=yes
  tags: ['deploy']
  with_items: ['grunt', 'pm2']

- name: build in project folder
  command: chdir={{ project_path }} grunt
  become: false
  tags: ['deploy']

- name: copy pm2 config.
  template: src=pm2.json.j2 dest={{ pm2_config_path }}
  notify: restart nginx
  tags: ['deploy']

- name: start node apps
  command: chdir={{ project_path }} pm2 startOrReload {{ pm2_config_path }}
  become: true
  tags: ['deploy']
